<?php

namespace ContainerHbJLtNJ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getImportCsvCommandService extends Padua_CsvImporter_KernelDevDebugContainer
{
    /**
     * Gets the public 'console.command.public_alias.Padua\CsvImporter\Command\ImportCsvCommand' shared autowired service.
     *
     * @return \Padua\CsvImporter\Command\ImportCsvCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/Command.php';
        include_once \dirname(__DIR__, 4).'/src/Command/ImportCsvCommand.php';

        return $container->services['console.command.public_alias.Padua\\CsvImporter\\Command\\ImportCsvCommand'] = new \Padua\CsvImporter\Command\ImportCsvCommand('/padua-csv_importer/var/tmp/');
    }
}
