<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerYjYDPfq\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerYjYDPfq/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerYjYDPfq.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerYjYDPfq\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerYjYDPfq\App_KernelDevDebugContainer([
    'container.build_hash' => 'YjYDPfq',
    'container.build_id' => 'c60ee9d1',
    'container.build_time' => 1626498998,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerYjYDPfq');
