<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerXGX2N2U\Padua_CsvImporter_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerXGX2N2U/Padua_CsvImporter_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerXGX2N2U.legacy');

    return;
}

if (!\class_exists(Padua_CsvImporter_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerXGX2N2U\Padua_CsvImporter_KernelDevDebugContainer::class, Padua_CsvImporter_KernelDevDebugContainer::class, false);
}

return new \ContainerXGX2N2U\Padua_CsvImporter_KernelDevDebugContainer([
    'container.build_hash' => 'XGX2N2U',
    'container.build_id' => '858162b5',
    'container.build_time' => 1626588524,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerXGX2N2U');
