<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container5biwyoo\Padua_CsvImporter_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container5biwyoo/Padua_CsvImporter_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container5biwyoo.legacy');

    return;
}

if (!\class_exists(Padua_CsvImporter_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container5biwyoo\Padua_CsvImporter_KernelDevDebugContainer::class, Padua_CsvImporter_KernelDevDebugContainer::class, false);
}

return new \Container5biwyoo\Padua_CsvImporter_KernelDevDebugContainer([
    'container.build_hash' => '5biwyoo',
    'container.build_id' => 'd7b128ef',
    'container.build_time' => 1626607969,
], __DIR__.\DIRECTORY_SEPARATOR.'Container5biwyoo');
