<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerOIpCKNg\Padua_CsvImporter_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerOIpCKNg/Padua_CsvImporter_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerOIpCKNg.legacy');

    return;
}

if (!\class_exists(Padua_CsvImporter_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerOIpCKNg\Padua_CsvImporter_KernelDevDebugContainer::class, Padua_CsvImporter_KernelDevDebugContainer::class, false);
}

return new \ContainerOIpCKNg\Padua_CsvImporter_KernelDevDebugContainer([
    'container.build_hash' => 'OIpCKNg',
    'container.build_id' => '2034af30',
    'container.build_time' => 1626512355,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerOIpCKNg');
